/**
 * Constants go here.
 * 
 * @date: 23/08/2014
 * @author: Nahid Akbar
 * @copyrightYear: 2014-2015
 * @copyright: National ICT Australia
 */

"use strict"

// 4 bit type
;
Object.defineProperty(exports, "__esModule", {
  value: true
});
var MARKER_CUSTOM = exports.MARKER_CUSTOM = 0x0;
var MARKER_REFERENCE = exports.MARKER_REFERENCE = 0x1;
var MARKER_OBJECT = exports.MARKER_OBJECT = 0x9;
var MARKER_ARRAY = exports.MARKER_ARRAY = 0xa;
var MARKER_STRING = exports.MARKER_STRING = 0xb;
var MARKER_FLOAT = exports.MARKER_FLOAT = 0xc;
var MARKER_INT = exports.MARKER_INT = 0xd;
var MARKER_UINT = exports.MARKER_UINT = 0xe;
var MARKER_SPECIAL = exports.MARKER_SPECIAL = 0xf;

// 4 bit SUBMARKER for MARKER_SPECIAL
var SPECIAL_SUBMARKER_NULL = exports.SPECIAL_SUBMARKER_NULL = 0x0;
var SPECIAL_SUBMARKER_UNDEFINED = exports.SPECIAL_SUBMARKER_UNDEFINED = 0x1;
var SPECIAL_SUBMARKER_FALSE = exports.SPECIAL_SUBMARKER_FALSE = 0x2;
var SPECIAL_SUBMARKER_TRUE = exports.SPECIAL_SUBMARKER_TRUE = 0x3;
var SPECIAL_SUBMARKER_PADDING = exports.SPECIAL_SUBMARKER_PADDING = 0x4;
var SPECIAL_SUBMARKER_PACKED = exports.SPECIAL_SUBMARKER_PACKED = 0x5;
var SPECIAL_SUBMARKER_BIG_ENDIAN = exports.SPECIAL_SUBMARKER_BIG_ENDIAN = 0x6;
var SPECIAL_SUBMARKER_LITTLE_ENDIAN = exports.SPECIAL_SUBMARKER_LITTLE_ENDIAN = 0x7;

// 4 bit SUBMARKER for MARKER_SPECIAL
var SIZE_SUBMARKER_VALUE_MIN = exports.SIZE_SUBMARKER_VALUE_MIN = 0x0;
var SIZE_SUBMARKER_VALUE_MAX = exports.SIZE_SUBMARKER_VALUE_MAX = 0x9;
var SIZE_SUBMARKER_256BITS = exports.SIZE_SUBMARKER_256BITS = 0xa;
var SIZE_SUBMARKER_128BITS = exports.SIZE_SUBMARKER_128BITS = 0xb;
var SIZE_SUBMARKER_64BITS = exports.SIZE_SUBMARKER_64BITS = 0xc;
var SIZE_SUBMARKER_32BITS = exports.SIZE_SUBMARKER_32BITS = 0xd;
var SIZE_SUBMARKER_16BITS = exports.SIZE_SUBMARKER_16BITS = 0xe;
var SIZE_SUBMARKER_8BITS = exports.SIZE_SUBMARKER_8BITS = 0xf;